### ISSUE TITLE
Unable to download through AltStore repo

### ISSUE THREAD

**Issue by miIktoast** [Balackburn/Apollo#1]
Install via AltStore repo not working

![89D377AD-45FF-4F86-B497-9F652D2DF61A](https://github.com/Balackburn/Apollo/assets/76277835/bb3ec34a-34df-44ad-ac55-83d6793c5f01)

**Comment by ghjimmy** [comment]
Same issue for me when I try to install

**Comment by Balackburn** [comment]
@ghjimmy @miIktoast It should work know, could you try again?

**Comment by norengo-sf** [comment]
Hi, 

I am also having the same issue. I tried again in the last few minutes and issue persists

**Comment by TheExcitedTech** [comment]
I am also having the same issue. I tried again in the last few minutes and issue persists

**Comment by jonathanlaniado** [comment]
@Balackburn, still running into this issue. Is there a fix?

**Comment by Balackburn** [comment]
@jonathanlaniado it should be fixed now

**Comment by jonathanlaniado** [comment]
Hmm unfortunately not. See here:

![image](https://github.com/Balackburn/Apollo/assets/8929491/519e8ac3-41de-4100-8b5d-d15f1bf0ccc9)
