### ISSUE TITLE
Reduce App IDs

### ISSUE THREAD

**Issue by BakaNode** [Balackburn/Apollo#11]
Not quite sure where to put this question so I’ll just apologize in advance since this isn’t really a bug per se.

is there anyway to reduce the number of App IDs this install takes? I love using Apollo but losing 7/10 pretty much means I can’t install anything else from SideStore.

Thank you for your time and glorious efforts!

**Comment by Balackburn** [comment]
Install the NO-EXTENSIONS version

**Comment by BakaNode** [comment]
I don’t see any mention of the no extensions version on SideStore, is there somewhere I’m not looking?

What all would be missing in this extension-less version?

**Comment by Balackburn** [comment]
Download the NO EXTENSIONS version from the release tab and install the .ipa manually, it’s not in the source

**Comment by BakaNode** [comment]
Ah! Thank you very much. Sorry for the possible stupid questions but I could't find any documentation for it anywhere. I assume this is how it'll go down when I reinstall in 7 days?

1. Apollo (core app) stays
2. Apollo ApolloIntentions (not sure what this does?) goes
3. Apollo Apollofari (some kind of Safari element?) goes
4. Apollo AthenaWidget (is this all the widgets?) goes
5. Apollo NotificationContentExtension (no more notifications?) goes
6. Apollo NotificationServiceExtension (no more notifications?) goes
7. Apollo Open in Apollo (the share sheet button?) goes
