### ISSUE TITLE
Add marketplace ID for AltStore PAL in the EU

### ISSUE THREAD

**Issue by peterge1998** [Balackburn/Apollo#17]
https://rileytestut.com/blog/2024/04/17/introducing-altstore-pal/
![IMG_0293](https://github.com/Balackburn/Apollo/assets/47355238/3651d024-feb5-4395-af55-52f188fc72ab)

**Comment by Balackburn** [comment]
I added one but it doesn't work, I think for now you can't add even a valid external source in Altstore PAL, you can't even add the official source : https://cdn.altstore.io/file/altstore/marketplace.json

**Comment by Balackburn** [comment]
Also, if I manage to get it to work (it's unlikely I can use a fake marketplaceID or a valid from another application and I don't think the application will be notarized by Apple), I'll have to create a separate source for Altstore PAL, as adding a marketplaceID breaks the source for normal Altstore (strange, I don't know why they did that).
![Screenshot 2024-04-23 at 10 48 53](https://github.com/Balackburn/Apollo/assets/93828569/977c6dc2-6a71-4c44-8929-3654f3ff84d3)

**Comment by alexalder** [comment]
Any update on this? I would switch if it was on the altstore

**Comment by Balackburn** [comment]
> Any update on this? I would switch if it was on the altstore

This app can't be notarized by Apple and adding a fake marketplaceID or a valid one from another app doesn't work.
