### ISSUE TITLE
Cannot Install - Requires Seven (7) App ID's

### ISSUE THREAD

**Issue by skymakai** [Balackburn/Apollo#19]
Requiring 7 App ID's is preventing me from installing via Altstore.  Would it be possible to reduce the number of App ID's required to 5 or less?

**Comment by Balackburn** [comment]
> Requiring 7 App ID's is preventing me from installing via Altstore.  Would it be possible to reduce the number of App ID's required to 5 or less?

Use the NO-EXTENSION .ipa avaiable in the latest release.

**Comment by skymakai** [comment]
Thank you.  I didn't see that.  Would it be possible to have a "no extension" version via the Altstore Source.  That way Altstore users could still see and install updates there.

**Comment by Balackburn** [comment]
> Thank you.  I didn't see that.  Would it be possible to have a "no extension" version via the Altstore Source?  That way Altstore users could still see and install updates there.

No sorry, the updates are so rare that it shouldn't be too hard to update.

**Comment by skymakai** [comment]
"...updates are so rare that it shouldn't be too hard to update."

Is this still true?  It seems as though there's an update every few days.

**Comment by Balackburn** [comment]
Hello you can do a fork and edit the script to create a no-extension source, I don't have much time and energy to do that now
