### ISSUE TITLE
Support new User Agent

### ISSUE THREAD

**Issue by dtantono** [Balackburn/Apollo#21]
Hi
it looks like some people find new problem with sideloaded app. I hope you can support this new user agent as well. 

https://new.reddit.com/r/apollosideloaded/comments/1ecbrb3/fix_for_the_infinite_loading_issue_and_additional/?sort=new

**Comment by Schobbish** [comment]
I just switched over to this version from an older tweaked IPA based on directions from some posts on r/apolloappbeta and no issues so far. This repo is forked from ImprovedCustomApi so I would expect an update soon either way.

**Comment by Cyphs** [comment]
It’s now updated.
