### ISSUE TITLE
Add to AltStore button doesn't work

### ISSUE THREAD

**Issue by Schobbish** [Balackburn/Apollo#22]
Clicking opens AltStore but gives error "The source “Apollo for Reddit” is not supported by this version of AltStore."

Running AltStore 1.7, iOS 17.5.1

![image](https://github.com/user-attachments/assets/424cc2a1-275c-4b71-b935-a1e0ff810b52)

**Comment by Balackburn** [comment]
Yes use altstore 2.0 instead, the 1.7 don't allow for custom sources

**Comment by Schobbish** [comment]
Ah I didn't see there was a newer version. Sorry about that.
