### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by abjugard** [Balackburn/Apollo#23]
When attempting to update to the latest version (v1.15.11-1.0.12) I get this error: `"Apollo" could not be installed.
The bundle ID "com.christianselig.Apollo" does not match the one specified by the source ("com.foo.Apollo").`

![image](https://github.com/user-attachments/assets/fba95d6a-cbfe-4b14-b939-2df361ae6fca)

Is the bundle ID of the last IPA different from the previous ones from this repo?

I'm installing using the latest SideStore build as I always have been, using the delete and re-add the source trick.

**Comment by abjugard** [comment]
Looks like the bundle ID on the IPA is changed in this version. Given how this works when you change the bundle ID like this everyone who wants to update is forced to set the app up again.

Any chance you might revert the bundle ID change in the IPA? Or at least choose one and commit to it for the future?

**Comment by blvdmd** [comment]
Also like to add that in the latest version 1.0.12, searching in multi-reddits does not work. While, when I reverted to earlier version it does.

**Comment by LazaroFilm** [comment]
I'm trying to install this for the first time and have the same error showing up.

**Comment by thexYeti** [comment]
You sure the one you had previously installed wasn’t apollopatcher? Either way, you can just change the bundle id yourself with sideloadly on pc, esign or modmyipa on device

**Comment by abjugard** [comment]
Bro you're not real.

Yes, I am 100% sure.

I have installed via this repo for the last 5-6 versions, I was actually the one who requested @Balackburn change to JefferyCA's build. I can't speak as to whether they had that idea on their own at the same time, but I asked for it and they listened.

**Comment by Balackburn** [comment]
Ah yes I forgot about that

**Comment by austinarchibald** [comment]
I installed the latest version posted 10 minutes ago. It installs fine, but now getting an error API when I try to add any of my reddit accounts to Apollo. Can't get past this. 

![image](https://github.com/user-attachments/assets/8d93f6a0-95a5-41ec-86d1-798d863bbef8)

**Comment by Balackburn** [comment]
I've definitely replaced com.foo.Apollo with com.christianselig.Apollo, you may have to reconfigure the application but it will be easier for future updates.

**Comment by abjugard** [comment]
> I've definitely replaced com.foo.Apollo with com.christianselig.Apollo, you may have to reconfigure the application but it will be easier for future updates.

All good, long as you commit to one it doesn't matter which to me. Thanks mate!

**Comment by thexYeti** [comment]
>Bro you’re not real. 

For giving you an answer on how to quickly solve your problem yourself? Alright lol

**Comment by abjugard** [comment]
> For giving you an answer on how to quickly solve your problem yourself? Alright lol

For insinuating I needed help. I know how to change the bundle ID, the issue as I saw it was that the bundle ID on the repo had changed, and everyone that's installed from the repo would now have to reinstall and re-setup their apps, client IDs, favourite subs, settings, etc. I thought that was unnecessary, so I reported that I thought the ID should be changed back *on the repo*...

**Comment by thexYeti** [comment]
Bro you’re not real.
