### ISSUE TITLE
RELEASE 19.37.2-1.1.4: (2024/09/18)

### ISSUE THREAD

**Issue by QiuIcs** [Balackburn/Apollo#28]
What's up with the version number? Also, didn't the ImprovedCustomAPI release the 1.1.5 v?

Update: hmmm weird, I could swear I saw the 1.1.5 release yesterday. The latest is indeed 1.1.4 now.

**Comment by lnlyssg** [comment]
I think it's actually YTLitePlus that has been uploaded! https://github.com/Balackburn/Apollo/issues/29

**Comment by Balackburn** [comment]
My bad used the wrong ipa for the build, also useless as they removed the 1.1.5 version released yesterday
