### ISSUE TITLE
Sideloadly installing YouTube with Apollo-19.37.2_improvedcustomapi-1.1.4

### ISSUE THREAD

**Issue by lnlyssg** [Balackburn/Apollo#29]
Not sure what's going on but the latest version shows and installs as YouTube (and has a completely different version number that looks more like a YTLitePlus one....) I'm assuming that this release is actually the YTLitePlus IPA, presumably uploaded in error!

<img width="112" alt="Screenshot 2024-09-18 at 22 22 42" src="https://github.com/user-attachments/assets/ba65c4b6-4743-4138-8c81-8e456a05cc6a">

Previous version is fine:
<img width="102" alt="Screenshot 2024-09-18 at 22 23 53" src="https://github.com/user-attachments/assets/1cfa99f5-dfc6-4463-9732-953704a10e6e">

**Comment by osxdoc** [comment]
Same problem here

**Comment by metroidmen** [comment]
Same issue here. Bizarre

**Comment by Balackburn** [comment]
My bad used the wrong ipa for the build, also useless as they removed the 1.1.5 version released yesterday
