### ISSUE TITLE
Better tweak to inject

### ISSUE THREAD

**Issue by abjugard** [Balackburn/Apollo#5]
Any chance you would consider switching from Artemis to [Apollo-ImprovedCustomApi](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi)? It's actively developed and solves irritating issues like the share links (`reddit.com/r/subreddit/s/xxxxxx`), and is apparently working on getting back the `New Comments Highlightifier` feature I have definitely been missing!

**Comment by Balackburn** [comment]
Hello it's done
