### ISSUE TITLE
Possible to upload a separate ipa with app extensions removed?

### ISSUE THREAD

**Issue by Jasonxu5** [Balackburn/Apollo#6]
Since SideStore only allows a maximum of 10 App IDs, would it possible for subsequent releases to upload a separate .ipa with the extensions below removed?
![extensions](https://github.com/Balackburn/Apollo/assets/22270527/4092f283-a119-4677-8dfd-df03abe8a930)

I previously removed these extensions with Sideloadly and most of the functionality still worked fine. I believe this only disables notifications and the iOS Widget

This is completely optional but it would definitely be a time saver for those that don't have any need for those features

**Comment by Balackburn** [comment]
Hello I was going to do it but Sideloadly tells me it doesn't have any Plugins (Extensions)
<img width="570" alt="Capture d’écran 2023-12-06 à 21 15 39" src="https://github.com/Balackburn/Apollo/assets/93828569/eb1ccbcf-a749-478c-804f-9114a89dfe24">

**Comment by Jasonxu5** [comment]
Thanks for doing this!

Unfortunately I can't delete the App IDs so I need to wait 7 days for them to expire. Feel free to close this issue for now and I'll post an update next week

**Comment by Jasonxu5** [comment]
@Balackburn Downloaded the ipa with no extensions and confirmed that it works with no issues. Thanks again!
