### ISSUE TITLE
Apollo version

### ISSUE THREAD

**Issue by abjugard** [Balackburn/Apollo#8]
Hmm, SideStore isn't offering to update Apollo for me, could that be because the version in the repo json is the same as the installed version?

**Comment by Balackburn** [comment]
> Hmm, SideStore isn't offering to update Apollo for me, could that be because the version in the repo json is the same as the installed version?

I think their is a bug with Sidestore, it doesn't show new updates you have to remove the repo add it again and reinstall the Apollo app

**Comment by Balackburn** [comment]
> > Hmm, SideStore isn't offering to update Apollo for me, could that be because the version in the repo json is the same as the installed version?
> 
> I think their is a bug with Sidestore, it doesn't show new updates you have to remove the repo add it again and reinstall the Apollo app 

Or maybe my apps.json isn't correctly formatted for Sidestore 🤷‍♂️

**Comment by abjugard** [comment]
> > > Hmm, SideStore isn't offering to update Apollo for me, could that be because the version in the repo json is the same as the installed version?
> > 
> > 
> > I think their is a bug with Sidestore, it doesn't show new updates you have to remove the repo add it again and reinstall the Apollo app
> 
> Or maybe my apps.json isn't correctly formatted for Sidestore 🤷‍♂️

No idea, your workaround worked, unfortunate SideStore won't just show an update button.
